topics:
  - pdf-processing
  - offset-printing
  - book-preparation
  - arabic-books
  - rtl-support
  - print-layout
  - commercial-printing
  - flask-application
  - pymupdf
  - a3-printing
  - duplex-printing
  - page-imposition
  - print-automation
  - arabic-pdf
  - printing-press
